harish_ramesh/4week/11march/home/auto/config/routes.rb
Rails.application.routes.draw do
  root :to => 'cars#index'
  resources :brands
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

harish_ramesh/4week/11march/home/auto/app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :cars
end

harish_ramesh/4week/11march/home/auto/app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :brand, :optional => true
end

harish_ramesh/4week/11march/home/auto/app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @brands = Brand.all
  end

  def new
    @brand = Brand.new
  end

  def create
    brand = Brand.create brand_params
    redirect_to brand
  end

  def edit
    @brand = Brand.find params[:id]
  end

  def update
    brand = Brand.find params[:id]
    brand.update brand_params
    redirect_to brand
  end

  def show
    @brand = Brand.find params[:id]
  end

  def destroy
    brand = Brand.find params[:id]
    brand.destroy
    redirect_to brands_path
  end

  private # The following methods aren't accessible outside of this class.
  def brand_params
    # Strong params: white list of sanitised input -- stuff we are happy to let the user provide.
    params.require(:brand).permit(:name, :nation, :established, :image)
  end
end

harish_ramesh/4week/11march/home/auto/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    car = Car.create car_params
    redirect_to car
  end

  def edit
    @car = Car.find params[:id]
  end

  def update
    car = Car.find params[:id]
    car.update car_params
    redirect_to car
  end

  def show
    @car = Car.find params[:id]
  end

  def destroy
    car = Car.find params[:id]
    car.destroy
    redirect_to cars_path
  end

  private
  def car_params
    params.require(:car).permit(:name, :style, :power, :image, :brand_id)
  end
end

harish_ramesh/4week/11march/home/auto/app/helpers/brands_helper.rb
module BrandsHelper
end

harish_ramesh/4week/11march/home/auto/app/helpers/cars_helper.rb
module CarsHelper
end

harish_ramesh/4week/11march/home/auto/app/views/cars/_form.html.erb
<%= form_for @car do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :style %>
  <%= f.text_field :style %>
  <%= f.label :power %>
  <%= f.text_field :power %>
  <%= f.label :image %>
  <%= f.url_field :image, :required => true %>
  <%= f.label :brand_id %>
  <%= f.select :brand_id, Brand.pluck(:name, :id), :include_blank => true %>
  <%= f.submit %>
<% end %>

harish_ramesh/4week/11march/home/auto/app/views/cars/edit.html.erb
<h1>Edit Car</h1>

<%= render :partial => 'form' %>

harish_ramesh/4week/11march/home/auto/app/views/cars/index.html.erb
<h1>All Cars</h1>

<% @cars.each do |car| %>
  <%= link_to image_tag(car.image, :class => 'thumb', :alt => car.name), car %>
<% end %>

harish_ramesh/4week/11march/home/auto/app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render :partial => 'form' %>

harish_ramesh/4week/11march/home/auto/app/views/cars/show.html.erb
<h1><%= @car.name %></h1>

<%= image_tag @car.image, :class => 'feature', :alt => @car.name %>

<ul>
  <li>Name: <%= @car.name %></li>
  <% if @car.brand.present? %>
    <li>Brand: <%= link_to @car.brand.name, @car.brand %></li>
  <% end %>
  <li>Style: <%= @car.style %></li>
  <li>Power: <%= @car.power %></li>

</ul>

<div class="controls">
  <%= link_to "Edit car", edit_car_path(@car) %>
  <%= link_to "Delete car", @car, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
</div>